name: karmango
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Dependency Injection
  injectable: ^2.4.4
  get_it: ^7.7.0

  # Networking and HTTP
  pretty_http_logger: ^1.0.3
  http: ^1.2.2
  dio: ^5.5.0+1

  # NoSQL Database
  shared_preferences: ^2.0.18
  hive_flutter: ^1.1.0

  # Code Generation for Data Classes
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1

  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5

  # UI and Utilities
  cached_network_image: ^3.3.0
  gap: ^3.0.1
  flutter_svg: ^2.0.9
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  photo_view: ^0.15.0
  mask_text_input_formatter: ^2.7.0
  pinput: ^5.0.0
  step_progress_indicator: ^1.0.2
  url_launcher: ^6.2.3
  image_picker: ^1.0.7
  lottie: ^3.1.2
  rotated_corner_decoration: ^2.1.0+1
  card_swiper: ^3.0.1
  modal_bottom_sheet: ^3.0.0

  # File Handling and Storage
  path_provider: ^2.1.2
  file_picker_writable: ^2.1.0+1
  flutter_secure_storage: ^9.2.2

  # Utilities
  logger: ^2.3.0
  http_parser: ^4.0.2
  device_info_plus: ^10.1.0

  share_plus: ^10.0.1  
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  injectable_generator: ^2.6.2
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animation/
    - assets/fonts/manrope/
    # foods
    - assets/images/food/
    - assets/icons/food/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
          weight: 200
